sudo: required

services:
  - docker

before_install:
  - sudo docker build -f dockerfile.dev -t querrix_test .

script:
  - docker run querrix_test

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "AKIAXA76NSHN7HNZHEPZ"
  secret_access_key:
    secure: "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"
  region: 'eu-west-2'
  app: 'deployx'
  env: 'Deployx-env'
  bucket_name: querri_x_s3_bucket_deploy
  on:
    branch: master
  # edge: true
