sudo: required

services:
  - docker

before_install:
  - sudo docker build -f dockerfile.dev -t querrix_test .

script:
  - docker run querrix_test

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: 'eu-west-2'

  app: 'deployqx'
  env: 'Deployqx-env'
  bucket_name: 'elasticbeanstalk-eu-west-2-483180515803'
  bucket_path: 'querrix-bucket'
  on:
    branch: master
  # edge: true
