sudo: required

services:
  - docker

before_install:
  - sudo docker build -f dockerfile.dev -t querrix_test .

script:
  - docker run querrix_test

deploy:
  provider: elasticbeanstalk
  access_key_id: 'AKIAXA76NSHN7HNZHEPZ'
  secret_access_key: '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'
  region: 'eu-west-2'
  app: 'deployx'
  env: 'Deployx-env'
  bucket_name: 'elasticbeanstalk-eu-west-2-483180515803'
  bucket_path: ""
  on:
    branch: master
  # edge: true
