version: "3.9"  # optional since v1.27.0
services:
  web:
    container_name: node-server
    restart: always
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/code
    links:
      - mongo
  mongo:
    image: mongo
    volumes: data/db
volumes:
    data: